name: Build and upload frameworks

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build barthage
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Switch xcode version
        run: |
          sudo xcode-select -s /Applications/Xcode_16.3.app

      - name: Copy libs
        run: |
          mkdir -p /Applications/Xcode_16.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc
          cp -R arc/* /Applications/Xcode_16.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/
      - name: Set up GitHub access token
        run: echo "GITHUB_ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> $GITHUB_ENV
        
      - name: Carthage build
        run: |
          carthage build --platform ios --use-xcframeworks

      - name: Carthage check
        run: |
          cd Carthage/Build
          ls -l

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Frameworks
          path: |
            Carthage/Build/*.xcframework
