name: Xcode - Build and Analyze

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build Carthage
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Switch Xcode Version
        run: |
          sudo xcode-select -s /Applications/Xcode_16.3.app

      - name: Copy Libs
        run: |
          mkdir -p /Applications/Xcode_16.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc
          cp -R arc/* /Applications/Xcode_16.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/

      - name: Carthage Build
        run: |
          carthage build --platform ios --use-xcframeworks --verbose

      - name: Carthage Check
        run: |
          cd Carthage/Build
          ls -l

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BuiltFrameworks
          path: |
            Carthage/Build/*.xcframework
