name: Xcode - Build and Analyze

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build Carthage
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Carthage Build
        run: |
          carthage build --platform ios --use-xcframeworks --verbose

      - name: Carthage Check
        run: |
          cd Carthage/Build
          ls -l
